/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.VentanaEliminarUsuario.listaDrop;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import project2.Funciones;
import project2.NodoUsers;
import project2.ListaDoc;
import project2.NodoDoc;
import project2.Users;

/**
 *
 * @author Jose
 */
public class VentanaEliminarDocumento extends javax.swing.JFrame {
    /**
     * Creates new form VentanaEliminarDocumento
     */
    public Users carpetaDoc;
    public static Users listaDrop;
    
    public static Users enviar(){
        listaDrop = VentanaAgregarUsuario.enviar();
        return listaDrop;
    };
    
    public VentanaEliminarDocumento() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        Funciones fun =new Funciones();
        File f=new File("test//new.csv");
        Users listaUser=fun.Leer_csv(f);
        String usuarios =listaUser.returnUsers();
        String[] user = usuarios.split(",");
        User.setModel(new javax.swing.DefaultComboBoxModel(user));
        carpetaDoc = VentanaAgregarUsuario.enviar();
        
        Users DocumList = VentanaAgregarUsuario.enviar();
        documento.setEnabled(true);
        NodoUsers Nodo=DocumList.BuscarUser(User.getSelectedItem().toString());
        String selection="";
        if(Nodo.getDocuments()!=null){
            NodoDoc aux=Nodo.getDocuments().getpFirst();
            while(aux!=null){
                selection+= aux.getNombre()+",";
                aux=aux.getpNext();
            }
        }
        String[] toSel =selection.split(",");
        documento.setModel(new javax.swing.DefaultComboBoxModel(toSel));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        User = new javax.swing.JComboBox<>();
        documento = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ELIMINAR DOCUMENTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel2.setText("ID USUARIO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 85, -1, -1));

        jLabel3.setText("NOMBRE DEL DOCUMENTO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        User.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        User.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                UserItemStateChanged(evt);
            }
        });
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        documento.setEnabled(false);
        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });
        getContentPane().add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        NodoUsers Nodo=carpetaDoc.BuscarUser(User.getSelectedItem().toString());
        NodoDoc doc=Nodo.BuscarDoc(documento.getSelectedItem().toString());
        ListaDoc lisDoc= Nodo.getDocuments();
        lisDoc.delByName(doc.getNombre());
        carpetaDoc.BuscarUser(User.getSelectedItem().toString()).setDocuments(lisDoc);
        listaDrop = carpetaDoc;
        
        NodoUsers Nodos=carpetaDoc.BuscarUser(User.getSelectedItem().toString());
        String selection="";
        if(Nodo.getDocuments()!=null){
            NodoDoc aux=Nodos.getDocuments().getpFirst();
            while(aux!=null){
                selection+= aux.getNombre()+",";
                aux=aux.getpNext();
            }
        }
        String[] toSel =selection.split(",");
        documento.setModel(new javax.swing.DefaultComboBoxModel(toSel));
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        
    }//GEN-LAST:event_UserActionPerformed

    private void UserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_UserItemStateChanged
        documento.setEnabled(true);
        NodoUsers Nodo=carpetaDoc.BuscarUser(User.getSelectedItem().toString());
        String selection="";
        if(Nodo.getDocuments()!=null){
            NodoDoc aux=Nodo.getDocuments().getpFirst();
            while(aux!=null){
                selection+= aux.getNombre()+",";
                aux=aux.getpNext();
            }
        }
        String[] toSel =selection.split(",");
        documento.setModel(new javax.swing.DefaultComboBoxModel(toSel));
        
        
    }//GEN-LAST:event_UserItemStateChanged

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEliminarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEliminarDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> User;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
