/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import static Interfaces.VentanaAgregarDocumento.listaDocs;
import static Interfaces.VentanaEliminarDocumento.listaDrop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import project2.Funciones;
import project2.Hash_table;
import project2.MonticuloMin;
import project2.NodoArbol;
import project2.NodoDoc;
import project2.Users;


/**
 *
 * @author Jose
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    public static MonticuloMin monticuloMin;
    public static Hash_table hashTable;
    
    public static Hash_table enviarHashTable(){
        return hashTable;
    };
    
    public static MonticuloMin enviarmonticuloMin(){
        return monticuloMin;
    };
    
    public File fichero;
    public Users usuarios;
    
    public Timer t;
    public int dias;
    public int horas;
    public int minutos;
    public int segundos;
    private ActionListener action =new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            
            
            segundos++;
            if(segundos==60){
                segundos=0;
                minutos++;
            }
            if(minutos==60){
                minutos=0;
                horas++;
            }
            if(horas==24){
                horas=0;
                dias++;
            }
            actualizar();
        }
    };
    
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    
    
    private void actualizar(){
        String time="Dias: "+dias+" Horas: "+ (horas<=9?"0":"")+horas +" Minutos: "+ (minutos<=9?"0":"")+minutos +" Segundos: "+ (segundos<=9?"0":"")+segundos;
        this.reloj.setText(time);
    }
    
    public VentanaPrincipal() {
        initComponents();
        Hash_table hash_tablee = new Hash_table(10000);
        MonticuloMin monticulo= new MonticuloMin();
        monticuloMin = monticulo;
        hashTable = hash_tablee;
        
        
        this.setLocationRelativeTo(null);
        t=new Timer(1000,action);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnAggUsuario = new javax.swing.JButton();
        btnAggDocumento = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnDelDocumento = new javax.swing.JButton();
        btnDelUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        reloj = new javax.swing.JLabel();
        btnImprimir1 = new javax.swing.JButton();
        btnImprimir2 = new javax.swing.JButton();
        btnImprimir3 = new javax.swing.JButton();
        btnImprimir4 = new javax.swing.JButton();
        btnImprimir5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jButton1.setText("ELIMINAR USUARIO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(433, 527));
        setMinimumSize(new java.awt.Dimension(433, 527));
        setPreferredSize(new java.awt.Dimension(433, 527));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAggUsuario.setText("AGREGAR USUARIO");
        btnAggUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAggUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 248, -1));

        btnAggDocumento.setText("AGREGAR DOCUMENTO");
        btnAggDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAggDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 248, -1));

        btnImprimir.setText("AGREGAR A COLA DE IMPRESION");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        btnDelDocumento.setText("ELIMINAR DOCUMENTO");
        btnDelDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelDocumentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 248, -1));

        btnDelUsuario.setText("ELIMINAR USUARIO");
        btnDelUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 248, -1));

        jLabel2.setText("reloj:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 15, -1, -1));

        reloj.setText("00:00:00:00");
        getContentPane().add(reloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 15, -1, -1));

        btnImprimir1.setText("VER LA COLA DE IMPRESION");
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 248, -1));

        btnImprimir2.setText("CARGAR DATOS");
        btnImprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 248, -1));

        btnImprimir3.setText("USUARIOS Y DOCUMENTOS");
        btnImprimir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 248, -1));

        btnImprimir4.setText("IMPRIMIR");
        btnImprimir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 248, -1));

        btnImprimir5.setText("ELIMINAR DE COLA");
        btnImprimir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 248, -1));

        jLabel7.setText("BIENVENIDO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        jTextPane4.setEditable(false);
        jTextPane4.setDragEnabled(false);
        jTextPane4.setEnabled(false);
        jTextPane4.setFocusCycleRoot(false);
        jTextPane4.setFocusTraversalKeysEnabled(false);
        jTextPane4.setRequestFocusEnabled(false);
        jTextPane4.setVerifyInputWhenFocusTarget(false);
        jScrollPane4.setViewportView(jTextPane4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 100, 30));

        jLabel3.setText("Nota: imprimir tiene un tiempo extra colocado por nosotros");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        jLabel4.setText("para simular la impresion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1)))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 520, 530, 110));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Alta_montaña,_verde,_hierba,_piscina_de_aguaPapel pintado_1024x768[10wallpaper.com].jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggUsuarioActionPerformed
        // TODO add your handling code here:
        VentanaAgregarUsuario venaddus = new VentanaAgregarUsuario();
        venaddus.setVisible(true);
    }//GEN-LAST:event_btnAggUsuarioActionPerformed

    private void btnAggDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggDocumentoActionPerformed
        // TODO add your handling code here:
        
        VentanaAgregarDocumento venadddoc = new VentanaAgregarDocumento();
        venadddoc.setVisible(true);
        
        
        
    
    }//GEN-LAST:event_btnAggDocumentoActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        VentanaImprimirDocumento venprint = new VentanaImprimirDocumento(this.dias,this.horas,this.minutos,this.segundos);
        venprint.setVisible(true);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnDelUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelUsuarioActionPerformed
        // TODO add your handling code here:
        
        listaDocs = VentanaEliminarUsuario.enviar();
        VentanaEliminarUsuario vendelus = new VentanaEliminarUsuario();
        vendelus.setVisible(true);
    
    }//GEN-LAST:event_btnDelUsuarioActionPerformed

    private void btnDelDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelDocumentoActionPerformed
        // TODO add your handling code here:
        VentanaEliminarDocumento vendeldoc = new VentanaEliminarDocumento();
        vendeldoc.setVisible(true);
    }//GEN-LAST:event_btnDelDocumentoActionPerformed

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
    try{
        monticuloMin.makeAFamily();
        monticuloMin.pntAllelmnt();
        monticuloMin.ShowHeap();
    }
    
    catch(Exception e){
        JOptionPane.showMessageDialog(null, "Algo ha salido mal, por favor intentelo de nuevo","Error",JOptionPane.INFORMATION_MESSAGE);
    }

    }//GEN-LAST:event_btnImprimir1ActionPerformed

    private void btnImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir2ActionPerformed
        Funciones fc = new Funciones();
        JFileChooser fx = new JFileChooser();

        int seleccion = fx.showOpenDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {

            fichero = fx.getSelectedFile();
            usuarios=fc.Leer_csv(fichero);
            fc.writeTxt(usuarios);
            File f=new File("test//new.csv");
            fichero.renameTo(f);
        }
    }//GEN-LAST:event_btnImprimir2ActionPerformed

    private void btnImprimir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir3ActionPerformed
        try{
            Users usuarios=VentanaAgregarUsuario.enviar();
            usuarios.imprimirTodo();
            if(!hashTable.isEmpty()){
                hashTable.imprimir(usuarios);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Algo ha salido mal, por favor intentelo de nuevo","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnImprimir3ActionPerformed

    private void btnImprimir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir4ActionPerformed
    try{    
        NodoArbol nodo=monticuloMin.eliminarMinimo();
        String info ="";
        while(nodo!=null){
            info += "Nombre: "+nodo.getData().getNombre()+" Tipo: "+nodo.getData().getTipo()+"\n";
            
            imprimir print=new imprimir(info);
            print.setVisible(true);
            nodo=monticuloMin.eliminarMinimo();
            print.setVisible(false);
        }
        imprimir print=new imprimir(info);
        hashTable = new Hash_table(10000);
        print.setVisible(true);
    }
    catch(Exception e){
            JOptionPane.showMessageDialog(null, "Algo ha salido mal, por favor intentelo de nuevo","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnImprimir4ActionPerformed

    private void btnImprimir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir5ActionPerformed
        EliminarDocCola DelCola=new EliminarDocCola();
        DelCola.setVisible(true);
    }//GEN-LAST:event_btnImprimir5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAggDocumento;
    private javax.swing.JButton btnAggUsuario;
    private javax.swing.JButton btnDelDocumento;
    private javax.swing.JButton btnDelUsuario;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnImprimir2;
    private javax.swing.JButton btnImprimir3;
    private javax.swing.JButton btnImprimir4;
    private javax.swing.JButton btnImprimir5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JLabel reloj;
    // End of variables declaration//GEN-END:variables
}
